### ISSUE TITLE
Support Hipster local brews

### ISSUE THREAD

**Issue by peterlamar** [jorisroovers/worldofbeers#1]
As a Hipster, I need to feel superior when choosing a beer so that I can sustain my self esteem. Clearly, I cannot do mainstream beers and need a 'microbrew' option in each country so that I can continue being smug and look down at people who consume 'mainstream' beers.

**Comment by jorisroovers** [comment]
Got it, will add a "feeling hipster" option once we've got a proper DB of the mainstream beers build out :-)
